### ISSUE TITLE
An error message is displayed when the command"mpirun -np 8 lmp_mpi -in.ch"

### ISSUE THREAD

**Issue by 12jscvb** [DiracMD/CVHD#1]
An error message that 'Cannot open molecule file dodecane.txt' is displayed when entering the command "mpirun -np 8 lmp_mpi -in.ch" in terminal . I do not search this file on github, Could you provide dodecane.txt file?  Thank you for help! Best wishes 

tip: the error message is saved in log.lammps

[log.txt](https://github.com/Eipgen/CVHD_tutorial/files/13973073/log.txt)

**Comment by Eipgen** [comment]
sorry, i forgot add `dodecane.txt` file, now you can find it in the repo

**Comment by Eipgen** [comment]
> sorry, i forgot add `dodecane.txt` file, now you can find it in the repo

**Comment by 12jscvb** [comment]
> > sorry, i forgot add `dodecane.txt` file, now you can find it in the repo

ok, thank you
