### ISSUE TITLE
the error that 'colvars: Writing the state file "rest.colvars.state". free(): invalid size'  exists  when running the CVHD, but I could't fix this problem. Thank you for help

### ISSUE THREAD

**Issue by 12jscvb** [DiracMD/CVHD#2]
Follow the instructions on github. when running CVHD+ lammps for a while, the following error message appears:
![Screenshot from 2024-01-22 13-17-19](https://github.com/Eipgen/CVHD_tutorial/assets/145745956/79e0f3a2-a006-4842-8106-920589f5d4ea)

I found that the generated rest.colvars.state file is empty. I doubt if there is a problem in compiling the stage of  lammps+CVHD. At compile time, when I type the command' make mpi ' in the terminal (I am using openmpi v4.1.4), I get the following error message:
‘/usr/bin/ld: math_special.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object;  recompile with -fPIE
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:89: ../lmp_mpi] Error 1
make[1]: Leaving directory '/home/cv/Public/lammps-7Aug19/src/Obj_mpi'
make: *** [Makefile:217: mpi] Error 2’
 Then, instead of the old mathc_special.o  file, I use mathc_special.o file  generated by the command 'g++ -c -o math_special.o math_special.cpp -fPIE ' . Finally,I complete the Compilation process。 

So, will this operation cause the software to run incorrectly？
Thank you! Best wishes

**Comment by Eipgen** [comment]
I thought it's a problem about lammps with openmpi, you can try a older openmpi.

**Comment by 12jscvb** [comment]
> I thought it's a problem about lammps with openmpi, you can try a older openmpi.

According to the tutorial, use openmpi v4.1.0? Or a version lower than 4.1.0

**Comment by Eipgen** [comment]
you can use openmpi 3.1.1.

**Comment by 12jscvb** [comment]
> you can use openmpi 3.1.1.

ok, l will try it ,thank you for help

**Comment by 12jscvb** [comment]
Hi ,Professor.  I complie the lammps+colvars with openmpi v3.1.1, however, it encounters the same error, as follows
‘/usr/bin/ld: math_special.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:89: ../lmp_mpi] Error 1
make[1]: Leaving directory '/home/cv/Public/lammps-7Aug19/src/Obj_mpi'
make: *** [Makefile:217: mpi] Error 2’

I've tried a lot of things, but it still hasn't worked out. Could you give me some advice
