### ISSUE TITLE
For the output result of CVHD , how to obtain the value of global collective variable（cv） η according to the formula?

### ISSUE THREAD

**Issue by 12jscvb** [DiracMD/CVHD#3]
Hello!  I am new to CVHD. I encounter some difficult problems, may I ask you for advice? (The attachment is the out.colvars.traj file)

The out.colvars.traj file obtained by lammps running the CVHD method through the modified colvars module, the first line of the content is 'step', 'coord', and 'E_hd'. I originally thought that the 'coord' parameter represented the global collective variable(cv) η mentioned in the paper, but I found that its value gradually increased from  e-01 to e+02 . What is the explanation of the coord parameter? How does this parameter relate to the global collective variable η mentioned in the paper? (or how to get the η value) 

 Thank you very much for help!

[1.txt](https://github.com/Eipgen/CVHD_tutorial/files/14392891/1.txt)

**Comment by Eipgen** [comment]
you can find explanation in `example.multibond`
```bash
colvarsTrajFrequency 10000 # output every 10000 steps
colvarsRestartFrequency 10000
indexFile atoms.ndx # this example reads an index file

colvar {
  name coord

  width 0.05               # CV width

  bondBreakMulti {
    group1 {
      indexGroup carbon    # Group of first bond partners
    }
    group2 {
      indexGroup hydrogen  # Group of second bond partners
    }
    rmin11 1.40            # rmin of 1-1 interaction
    rmax11 2.00            # rmax of 1-1 interaction
    rcut11 1.80            # rcut of 1-1 interaction
    rmin12 1.00            # and so on...
    rmax12 1.60
    rcut12 1.50
    rmin22 0.10            # here, the 2-2 interaction is excluded
    rmax22 0.10            # by setting rcut to be very small
    rcut22 0.10            
    waitTime 5000          # t_w, in time steps
    power 6                # p
  }
}

cvhd {
  name hd                  # Something descriptive (or not)
  colvars coord            # The CV (ONLY ONE ALLOWED!)
  outputEnergy on          # Communicate energy to calling program
  dynamicBias on           # Toggle dynamic/static bias
  maxBias 10.0             # Maximal bias in the static case (now not active), in Energy Units
  hillWidth 1.0            # Width of Gaussian (see metadynamics in Colvars)
  hillWeight 0.25          # Height of Gaussian (see metadynamics in Colvars), in Energy Units
  newHillFrequency 1000    # Frequency of Gaussian addition (see metadynamics in Colvars), in # time steps
  wellTempered off         # Use Well-Tempered Metadynamics (now not active)
  biasTemperature 5000     # Well-Tempered Metadynamics bias temperature
} 
`
it's CVs of the systems.

**Comment by 12jscvb** [comment]
thank you for comment. I have followed the example above, but found that the output result did not have a hypertime value and an&nbsp;&nbsp;&nbsp;η&nbsp;. Do l need to write relevant script to calculate these two parameter values according to relevant literature? thank you




---Original---
From: "Jin ***@***.***&gt;
Date: Thu, Feb 29, 2024 20:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Eipgen/CVHD_tutorial] For the output result of CVHD , how to obtain the value of global collective variable（cv） η according to the formula? (Issue #3)




 
you can find explanation in example.multibond
 colvarsTrajFrequency 10000 # output every 10000 steps colvarsRestartFrequency 10000 indexFile atoms.ndx # this example reads an index file colvar {   name coord   width 0.05               # CV width   bondBreakMulti {     group1 {       indexGroup carbon    # Group of first bond partners     }     group2 {       indexGroup hydrogen  # Group of second bond partners     }     rmin11 1.40            # rmin of 1-1 interaction     rmax11 2.00            # rmax of 1-1 interaction     rcut11 1.80            # rcut of 1-1 interaction     rmin12 1.00            # and so on...     rmax12 1.60     rcut12 1.50     rmin22 0.10            # here, the 2-2 interaction is excluded     rmax22 0.10            # by setting rcut to be very small     rcut22 0.10                 waitTime 5000          # t_w, in time steps     power 6                # p   } } cvhd {   name hd                  # Something descriptive (or not)   colvars coord            # The CV (ONLY ONE ALLOWED!)   outputEnergy on          # Communicate energy to calling program   dynamicBias on           # Toggle dynamic/static bias   maxBias 10.0             # Maximal bias in the static case (now not active), in Energy Units   hillWidth 1.0            # Width of Gaussian (see metadynamics in Colvars)   hillWeight 0.25          # Height of Gaussian (see metadynamics in Colvars), in Energy Units   newHillFrequency 1000    # Frequency of Gaussian addition (see metadynamics in Colvars), in # time steps   wellTempered off         # Use Well-Tempered Metadynamics (now not active)   biasTemperature 5000     # Well-Tempered Metadynamics bias temperature }  ` it's CVs of the systems.
